version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "datasette-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-b0wlb2reqeoz"
s3_prefix = "datasette-test"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

